export const interiors = [
    { id: 1, name: 'Living Room' },
    { id: 2, name: 'Bedroom' },
    { id: 3, name: 'Kitchen' },
    { id: 4, name: 'Bathroom' },
    { id: 5, name: 'Dining Room' },
    { id: 6, name: 'Office' },
    { id: 7, name: 'Kids Room' },
    { id: 8, name: 'Hallway' },
    { id: 9, name: 'Outdoor' },
    { id: 10, name: 'Garden' },
    { id: 11, name: 'Balcony' },
    { id: 12, name: 'Garage' },
    { id: 13, name: 'Gym' },
    { id: 14, name: 'Spa' },
    { id: 15, name: 'Pool' },
    { id: 16, name: 'Laundry Room' },
    { id: 17, name: 'Closet' },
    { id: 18, name: 'Stairs' },
    { id: 19, name: 'Home Bar' },
    { id: 20, name: 'Basement' },
    { id: 21, name: 'Attic' },
    { id: 22, name: 'Home Theater' },
    { id: 23, name: 'Library' },
    { id: 24, name: 'Studio' },
    { id: 25, name: 'Patio' },
    { id: 26, name: 'Terrace' },
];